trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true


- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'service-jk'
    command: 'restore'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'service-jk'
    command: 'build'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'service-jk'
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release -o $(Build.SourcesDirectory)/app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/app'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'   # Jo tumne PublishBuildArtifacts mein diya tha
    downloadPath: '$(System.ArtifactsDirectory)'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'sshConnection'
    sourceFolder: '$(System.ArtifactsDirectory)/drop'
    contents: '**'
    targetFolder: 'elearnbackend'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'sshConnection'
    runOptions: 'commands'
    commands: |
      cd /home/ec2-user/elearnbackend
      dotnet ElearnBackend.dll &
    readyTimeout: '20000'




