trigger:
 branches:
    include:
      - main
pool:
 vmImage: "ubuntu-latest"
stages:
  - stage: 
    jobs:
      - job: 
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
        - task: Docker@2
          inputs:
            containerRegistry: 'Dockerhub-registry'
            repository: 'jksoam777/nginx'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'